"Resource/UI/arenawinpanel.res"
{
	"WinningTeamLabelDropshadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WinningTeamLabelDropshadow"
		"font"			"ScoreboardTeamName"
		"fgcolor"		"black"
		"xpos"			"1"
		"ypos"			"79"
		"zpos"			"1"
		"wide"			"442"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%WinningTeamLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}
	"LosingTeamLabelDropshadow"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"WinningTeamLabelDropshadow"
		"font"			"ScoreboardTeamName"
		"fgcolor"		"black"
		"xpos"			"1"
		"ypos"			"79"
		"zpos"			"1"
		"wide"			"442"
		"tall"			"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"%LosingTeamLabel%"
		"textAlignment"		"Center"
		"dulltext"		"0"
		"brighttext"		"0"
	}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	"ArenaWinPanelScores"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"ArenaWinPanelScores"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"

		"BlueTeamLabelBG"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"BlueTeamLabelBG"
			"xpos"			"0"
			"ypos"			"10"
			"zpos"			"0"
			"wide"			"f0"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"bluLabelBG"
		}

		"BlueTeamLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"BlueTeamLabelDropshadow"
			"xpos"			"c-200"
			"ypos"			"10"
			"zpos"			"1"
			"wide"			"140"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%blueteamname%"
			"textAlignment"		"east"
			"textinsetx"	"20"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor"		"winpanelText"
			"bgcolor_override"	"bluLabelBG"
			"auto_wide_tocontents"	"0"
		}
		"BlueTeamScoreDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"BlueTeamScoreDropshadow"
			"xpos"			"c-60"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"60"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontMedium"
			"fgcolor"		"winpanelText"
			"bgcolor_override"	"bluScoreBG"
			"auto_wide_tocontents"	"0"
		}
		"RedTeamLabelDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RedTeamLabelDropshadow"
			"xpos"			"c60"
			"ypos"			"10"
			"zpos"			"1"
			"wide"			"f0"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%redteamname%"
			"textAlignment"		"west"
			"textinsetx"	"20"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor"		"winpanelText"
			"bgcolor_override"	"redLabelBG"
			"auto_wide_tocontents"	"0"
		}
		"RedTeamScoreDropshadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"RedTeamScoreDropshadow"
			"xpos"			"c0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"60"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%redteamscore%"
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontMedium"
			"fgcolor"		"winpanelText"
			"bgcolor_override"	"redScoreBG"
			"auto_wide_tocontents"	"0"
		}
		// Trash

			"ArenaStreaksBG"
			{
				"ControlName"	"ScalableImagePanel"
				"fieldName"		"ArenaStreaksBG"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}

			"ArenaStreakLabel"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"ArenaStreakLabel"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}

			"BlueTeamLabel"
			{
				"ControlName"		"CExLabel"
				"fieldName"		"BlueTeamLabel"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}

			"BlueTeamScore"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"BlueTeamScore"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}

			"RedTeamLabel"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"RedTeamLabel"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}

			"RedTeamScore"
			{
				"ControlName"		"CExLabel"
				"fieldName"		"RedTeamScore"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}

			"BlueScoreBG"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"BlueScoreBG"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}
			"RedScoreBG"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"RedScoreBG"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"0"
				"tall"			"0"
				"visible"		"0"
				"enabled"		"0"
			}
	}

	"WinPanelBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"WinPanelBG"
		"xpos"			"0"
		"ypos"			"c30"
		"zpos"			"0"
		"wide"			"f0"
		"tall"			"60"
		"scaleImage"	"1"
		"alpha"			"100"
	}

	// Podium

	"mvp1podium"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"mvp1podium"
		"xpos"			"c-25"
		"ypos"			"c-135"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"125"
		"labelText"		"="
		"textAlignment"		"south"
		"textinsetx"	"0"
		"textinsety"	"-5"
		"font"			"MenuIcons"
		"fgcolor_override"	"trophyOne"
		"bgcolor_override"	"podiumOne"
		"auto_wide_tocontents"	"0"
	}

	"mvp1base"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"mvp1base"
		"xpos"			"c-25"
		"ypos"			"c20"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"10"
		"fillcolor"		"podiumOne"
		"border"		"NoBorder"
	}

	"mvp2podium"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"mvp2podium"
		"xpos"			"c-200"
		"ypos"			"c-110"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"100"
		"labelText"		"="
		"textAlignment"		"south"
		"textinsetx"	"0"
		"textinsety"	"-5"
		"font"			"MenuIcons"
		"fgcolor_override"	"trophyTwo"
		"bgcolor_override"	"podiumTwo"
		"auto_wide_tocontents"	"0"
	}

	"mvp2base"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"mvp2base"
		"xpos"			"c-200"
		"ypos"			"c20"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"10"
		"fillcolor"		"podiumTwo"
		"border"		"NoBorder"
	}

	"mvp3podium"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"mvp3podium"
		"xpos"			"c150"
		"ypos"			"c-85"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"75"
		"labelText"		"="
		"textAlignment"		"south"
		"textinsetx"	"0"
		"textinsety"	"-5"
		"font"			"MenuIcons"
		"fgcolor_override"	"trophyThree"
		"bgcolor_override"	"podiumThree"
		"auto_wide_tocontents"	"0"
	}

	"mvp3base"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"mvp3base"
		"xpos"			"c150"
		"ypos"			"c20"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"10"
		"fillcolor"		"podiumThree"
		"border"		"NoBorder"
	}

	// Trophies

	"trophy1"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"trophy1"
		"xpos"			"12"
		"ypos"			"c122"
		"zpos"			"1"
		"wide"			"16"
		"tall"			"16"
		"labelText"		"="
		"textAlignment"		"center"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"MenuIcons"
		"fgcolor_override"	"trophyOne"
		"bgcolor_override"	"trophyBG"
		"auto_wide_tocontents"	"0"
	}

	"trophy2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"trophy2"
		"xpos"			"12"
		"ypos"			"c142"
		"zpos"			"1"
		"wide"			"16"
		"tall"			"16"
		"labelText"		"="
		"textAlignment"		"center"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"MenuIcons"
		"fgcolor_override"	"trophyTwo"
		"bgcolor_override"	"trophyBG"
		"auto_wide_tocontents"	"0"
	}

	"trophy3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"trophy3"
		"xpos"			"12"
		"ypos"			"c162"
		"zpos"			"1"
		"wide"			"16"
		"tall"			"16"
		"labelText"		"="
		"textAlignment"		"center"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"MenuIcons"
		"fgcolor_override"	"trophyThree"
		"bgcolor_override"	"trophyBG"
		"auto_wide_tocontents"	"0"
	}

	"WinningTeamLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"WinningTeamLabel"
		"xpos"			"0"
		"ypos"			"c30"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"60"
		"labelText"				"%WinningTeamLabel%"
		"textAlignment"			"west"
		"fgcolor_override"		"winpanelText"
		"font"					"NewFontHuge"
		"textinsetx"			"20"
		"auto_wide_tocontents"	"1"
	}

	"LosingTeamLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"WinningTeamLabel"
		"xpos"			"0"
		"ypos"			"c30"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"60"
		"textinsetx"	"20"
		"textAlignment"		"west"
		"labelText"			"%LosingTeamLabel%"
		"font"				"NewFontHuge"
		"fgcolor_override"	"winpanelText"
		"auto_wide_tocontents"	"1"
	}

	"WinReasonLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"WinReasonLabel"
		"xpos"				"0"
		"ypos"				"c90"
		"zpos"				"0"
		"wide"				"f0"
		"tall"				"30"
		"labelText"			"%WinReasonLabel%"
		"textAlignment"		"west"
		"textinsetx"		"20"
		"font"				"NewFontMedium"
		"fgcolor_override"	"winpanelText"
		"bgcolor_override"	"winpanelBar"
	}

	"DetailsLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DetailsLabel"
		"xpos"			"r310"
		"ypos"			"c30"
		"zpos"			"1"
		"wide"			"310"
		"tall"			"60"
		"labelText"		"%DetailsLabel%"
		"textAlignment"		"center"
		"centerwrap"	"1"
		"textinsetx"	"20"
		"textinsety"	"0"
		"font"			"NewFontMedium"
		"fgcolor_override"	"winpanelText"
		"bgcolor_override"	"blank"
		"auto_wide_tocontents"	"0"
	}
	
	"KillingBlowsThisRoundLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"PointsThisRoundLabel"
		"xpos"			"r310"
		"ypos"			"c90"
		"zpos"			"3"
		"wide"			"75"
		"tall"			"30"
		"labelText"			"Frags"
		"textAlignment"		"center"
		"font"				"NewFontSmall"
		"fgcolor_override"	"winpanelText"
	}

	"DamageThisRoundLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"DamageThisRoundLabel"
		"xpos"			"r235"
		"ypos"			"c90"
		"zpos"			"3"
		"wide"			"75"
		"tall"			"30"
		"labelText"		"Damage"
		"textAlignment"		"center"
		"font"			"NewFontSmall"
		"fgcolor_override"	"winpanelText"
	}
	
	"HealingThisRoundLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"PointsThisRoundLabel"
		"xpos"			"r160"
		"ypos"			"c90"
		"zpos"			"3"
		"wide"			"75"
		"tall"			"30"
		"labelText"		"Heals"
		"textAlignment"		"center"
		"font"			"NewFontSmall"
		"fgcolor_override"	"winpanelText"
	}
	
	"LifetimeThisRoundLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"PointsThisRoundLabel"
		"xpos"			"r85"
		"ypos"			"c90"
		"zpos"			"3"
		"wide"			"75"
		"tall"			"30"
		"labelText"		"Lifetime"
		"textAlignment"		"center"
		"font"			"NewFontSmall"
		"fgcolor_override"	"winpanelText"
	}

	"ShadedBar"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ShadedBar"
		"xpos"			"0"
		"ypos"			"30"
		"zpos"			"-1"
		"wide"			"f0"
		"tall"			"240"
		"fillcolor"		"winpanelTopBG"
		"PaintBackgroundType"	"0"
	}

	"ShadedBar2"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"ShadedBar2"
		"xpos"			"0"
		"ypos"			"c90"
		"zpos"			"-1"
		"wide"			"f0"
		"tall"			"240"
		"fillcolor"		"winpanelBottomBG"
	}

	"ArenaWinPanelWinnersPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"ArenaWinPanelWinnersPanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"zpos"			"3"

		"Player1Avatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"Player1Avatar"
			"xpos"			"c-25"
			"ypos"			"c-195"
			"wide"			"50"
			"tall"			"50"
			"image"			""
			"scaleImage"		"1"
		}
		"Player1Class"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Class"
			"xpos"			"c-25"
			"ypos"			"c-10"
			"zpos"			"1"
			"wide"			"50"
			"tall"			"30"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Name"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Name"
			"xpos"			"28"
			"ypos"			"c120"
			"wide"			"f0"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"west"
			"textinsetx"	"10"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Kills"
			"xpos"			"r310"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Damage"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Damage"
			"xpos"			"r235"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Healing"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Healing"
			"xpos"			"r160"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Lifetime"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Lifetime"
			"xpos"			"r85"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}

		"Player2Avatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"Player2Avatar"
			"xpos"			"c-200"
			"ypos"			"c-170"
			"wide"			"50"
			"tall"			"50"
			"image"			""
			"scaleImage"		"1"
		}
		"Player2Class"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Class"
			"xpos"			"c-200"
			"ypos"			"c-10"
			"zpos"			"1"
			"wide"			"50"
			"tall"			"30"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Name"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Name"
			"xpos"			"28"
			"ypos"			"c140"
			"wide"			"f0"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"west"
			"textinsetx"	"10"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Kills"
			"xpos"			"r310"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Damage"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Damage"
			"xpos"			"r235"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Healing"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Healing"
			"xpos"			"r160"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Lifetime"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Lifetime"
			"xpos"			"r85"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}

		"Player3Avatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"Player3Avatar"
			"xpos"			"c150"
			"ypos"			"c-145"
			"wide"			"50"
			"tall"			"50"
			"image"			""
			"scaleImage"		"1"
		}
		"Player3Class"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Class"
			"xpos"			"c150"
			"ypos"			"c-10"
			"zpos"			"1"
			"wide"			"50"
			"tall"			"30"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Name"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Name"
			"xpos"			"28"
			"ypos"			"c160"
			"wide"			"f0"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"west"
			"textinsetx"	"10"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Kills"
			"xpos"			"r310"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Damage"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Damage"
			"xpos"			"r235"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Healing"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Healing"
			"xpos"			"r160"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Lifetime"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Lifetime"
			"xpos"			"r85"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
	}
	"ArenaWinPanelLosersPanel"
	{
		"ControlName"		"EditablePanel"
		"fieldName"		"ArenaWinPanelWinnersPanel"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"zpos"			"3"

		"Player1Avatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"Player1Avatar"
			"xpos"			"c-25"
			"ypos"			"c-195"
			"wide"			"50"
			"tall"			"50"
			"image"			""
			"scaleImage"		"1"
		}
		"Player1Class"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Class"
			"xpos"			"c-25"
			"ypos"			"c-10"
			"zpos"			"1"
			"wide"			"50"
			"tall"			"30"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Name"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Name"
			"xpos"			"28"
			"ypos"			"c120"
			"wide"			"f0"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"west"
			"textinsetx"	"10"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Kills"
			"xpos"			"r310"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Damage"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Damage"
			"xpos"			"r235"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Healing"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Healing"
			"xpos"			"r160"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player1Lifetime"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player1Lifetime"
			"xpos"			"r85"
			"ypos"			"c120"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}

		"Player2Avatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"Player2Avatar"
			"xpos"			"c-200"
			"ypos"			"c-170"
			"wide"			"50"
			"tall"			"50"
			"image"			""
			"scaleImage"		"1"
		}
		"Player2Class"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Class"
			"xpos"			"c-200"
			"ypos"			"c-10"
			"zpos"			"1"
			"wide"			"50"
			"tall"			"30"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Name"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Name"
			"xpos"			"28"
			"ypos"			"c140"
			"wide"			"f0"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"west"
			"textinsetx"	"10"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Kills"
			"xpos"			"r310"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Damage"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Damage"
			"xpos"			"r235"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Healing"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Healing"
			"xpos"			"r160"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player2Lifetime"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player2Lifetime"
			"xpos"			"r85"
			"ypos"			"c140"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}

		"Player3Avatar"
		{
			"ControlName"		"CAvatarImagePanel"
			"fieldName"		"Player3Avatar"
			"xpos"			"c150"
			"ypos"			"c-145"
			"wide"			"50"
			"tall"			"50"
			"image"			""
			"scaleImage"		"1"
		}
		"Player3Class"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Class"
			"xpos"			"c150"
			"ypos"			"c-10"
			"zpos"			"1"
			"wide"			"50"
			"tall"			"30"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Name"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Name"
			"xpos"			"28"
			"ypos"			"c160"
			"wide"			"f0"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"west"
			"textinsetx"	"10"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Kills"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Kills"
			"xpos"			"r310"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Damage"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Damage"
			"xpos"			"r235"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Healing"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Healing"
			"xpos"			"r160"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
		"Player3Lifetime"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Player3Lifetime"
			"xpos"			"r85"
			"ypos"			"c160"
			"zpos"			"1"
			"wide"			"75"
			"tall"			"20"
			"labelText"		""
			"textAlignment"		"center"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"NewFontSmall"
			"fgcolor_override"	"winpanelText"
			"bgcolor_override"	"blank"
			"auto_wide_tocontents"	"0"
		}
	}

	// Trash

	"TopPlayersLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"		"TopPlayerLabel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
	}
}
