"Resource/UI/HudPlayerClass.res"
{

	//Font testing 
	"font6"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font6"
		"xpos"			"0"
		"ypos"			"60"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"6: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font6"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font7"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font7"
		"xpos"			"0"
		"ypos"			"70"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"7: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font7"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font8"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font8"
		"xpos"			"0"
		"ypos"			"80"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"8: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font8"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font9"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font9"
		"xpos"			"0"
		"ypos"			"90"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"9: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font9"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font10"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font10"
		"xpos"			"0"
		"ypos"			"100"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"10: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font10"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font11"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font11"
		"xpos"			"0"
		"ypos"			"120"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"11: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font11"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font12"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font12"
		"xpos"			"0"
		"ypos"			"140"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"12: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font12"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font13"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font13"
		"xpos"			"0"
		"ypos"			"160"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"13: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font13"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font14"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font14"
		"xpos"			"0"
		"ypos"			"180"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"14: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font14"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font15"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font15"
		"xpos"			"0"
		"ypos"			"200"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"15: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font15"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font16"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font16"
		"xpos"			"0"
		"ypos"			"220"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"16: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font16"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font17"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font17"
		"xpos"			"0"
		"ypos"			"240"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"17: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font17"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font18"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font18"
		"xpos"			"0"
		"ypos"			"260"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"18: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font18"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font19"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font19"
		"xpos"			"0"
		"ypos"			"280"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"19: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font19"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}
	"font20"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"font20"
		"xpos"			"0"
		"ypos"			"300"
		"zpos"			"0"
		"wide"			"0"
		"tall"			"480"
		"labelText"		"20: The quick brown fox jumps over the lazy dog. 1234567890"
		"textAlignment"		"north-west"
		"textinsetx"	"0"
		"textinsety"	"0"
		"font"			"font20"
		"fgcolor_override"	"mainWhite"
		"bgcolor_override"	"black"
		"auto_wide_tocontents"	"1"
	}

	"Secondly"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"Secondly"
		"xpos"			"0"
		"ypos"			"480"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"	

		"font21"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font21"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"21: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font21"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font22"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font22"
			"xpos"			"0"
			"ypos"			"20"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"22: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font22"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font23"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font23"
			"xpos"			"0"
			"ypos"			"40"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"23: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font23"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font24"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font24"
			"xpos"			"0"
			"ypos"			"70"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"24: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font24"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font25"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font25"
			"xpos"			"0"
			"ypos"			"100"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"25: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font25"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font26"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font26"
			"xpos"			"0"
			"ypos"			"130"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"26: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font26"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font27"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font27"
			"xpos"			"0"
			"ypos"			"160"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"27: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font27"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font28"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font28"
			"xpos"			"0"
			"ypos"			"190"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"28: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font28"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font29"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font29"
			"xpos"			"0"
			"ypos"			"220"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"29: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font29"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font30"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font30"
			"xpos"			"0"
			"ypos"			"250"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"30: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font30"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font31"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font31"
			"xpos"			"0"
			"ypos"			"290"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"31: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font31"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font32"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font32"
			"xpos"			"0"
			"ypos"			"320"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"32: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font32"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font33"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font33"
			"xpos"			"0"
			"ypos"			"360"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"33: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font33"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font34"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font34"
			"xpos"			"0"
			"ypos"			"400"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"34: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font34"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}
		"font35"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"font35"
			"xpos"			"0"
			"ypos"			"440"
			"zpos"			"0"
			"wide"			"0"
			"tall"			"480"
			"labelText"		"35: The quick brown fox jumps over the lazy dog. 1234567890"
			"textAlignment"		"north-west"
			"textinsetx"	"0"
			"textinsety"	"0"
			"font"			"font35"
			"fgcolor_override"	"mainWhite"
			"bgcolor_override"	"black"
			"auto_wide_tocontents"	"1"
		}	
	}



	// player class data
	"HudPlayerClass"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"HudPlayerClass"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"		
	}
	"PlayerStatusClassImage"
	{
		"ControlName"	"CTFClassImage"
		"fieldName"		"PlayerStatusClassImage"
		"xpos"			"c-20"
		"ypos"			"r80"
		"zpos"			"2"
		"wide"			"80"
		"tall"			"80"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/class_scoutred"
		"scaleImage"	"1"	
	}
	"PlayerStatusSpyImage"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusSpyImage"
		"xpos"			"3"
		"ypos"			"r67"
		"zpos"			"2"
		"wide"			"55"
		"tall"			"55"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/class_spyred"
		"scaleImage"	"1"	
		"teambg_2"		"../hud/class_spyred"
		"teambg_3"		"../hud/class_spyblue"			
	}	
	"PlayerStatusSpyOutlineImage"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusSpyOutlineImage"
		"xpos"			"-5"
		"ypos"			"r44"
		"zpos"			"7"
		"wide"			"27"
		"tall"			"27"
		"visible"		"0"
		"enabled"		"1"
		"image"			"../hud/class_spy_outline"
		"scaleImage"	"1"	
	}		
	"PlayerStatusClassImageBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"PlayerStatusClassImageBG"
		"xpos"			"10000"	
		"ypos"			"10000"
		"zpos"			"1"		
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"
		"image"			"../hud/character_red_bg"	
		"teambg_2"		"../hud/character_red_bg"
		"teambg_2_lodef"	"../hud/character_red_bg_lodef"
		"teambg_3"		"../hud/character_blue_bg"
		"teambg_3_lodef"	"../hud/character_blue_bg_lodef"
	}

	"separator"
	{
		"ControlName"	"ImagePanel"
		"fieldName"	"separator"
		"xpos"			"100"
		"ypos"			"r110"
		"wide"			"1"
		"tall"			"95"
		"fillcolor"		"separator"
	}

	"DamagedPlayerCircle"
	{
		"controlName" "CExLabel"
		"fieldName" "DamagedPlayerCircle"
		"visible" "1"
		"enabled" "1"
		"xpos" "c-50"
		"ypos" "c-50"
		"wide" "100"
		"tall"	 "100"
		"font" "CrosshairFont"
		"labelText" "O"
		"zpos"	 "-4"
		"textAlignment" "center"
		"fgcolor" "crosshairCircle"
	}

	"CrosshairLineHorizontal"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"CrosshairLineHorizontal"
		"xpos"				"c0"
		"ypos"				"0"
		"zpos"				"-1"
		"wide"				"1"
		"tall"				"480"
		"fillcolor"			"longasscrosshair"
	}
	"CrosshairLineVertical"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"CrosshairLineVertical"
		"xpos"				"0"
		"ypos"				"c0"
		"zpos"				"-1"
		"wide"				"f0"
		"tall"				"1"
		"fillcolor"			"longasscrosshair"
	}

	"classmodelpanelBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"classmodelpanelBG"
		"xpos"			"10000"	
		"ypos"			"10000"
		"zpos"			"1"		
		"wide"			"109"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"
		"image"				"../hud/character_red_bg_clipped"	
		"teambg_2"			"../hud/character_red_bg_clipped"
		"teambg_2_lodef"	"../hud/character_red_bg_lodef_clipped"
		"teambg_3"			"../hud/character_blue_bg_clipped"
		"teambg_3_lodef"	"../hud/character_blue_bg_lodef_clipped"
	}

	"classmodelpanel"
	{
		"ControlName"	"CTFPlayerModelPanel"
		"fieldName"		"classmodelpanel"
		
		"xpos"			"0"
		"ypos"			"r140"
		"zpos"			"2"		
		"wide"			"100"
		"tall"			"130"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		"render_texture"	"0"
		"fov"			"0"
		"allow_rot"		"0"

		"disable_speak_event"	"1"
				
		"model"
		{
			"force_pos"	"1"

			"angles_x" "0"
			"angles_y" "172"
			"angles_z" "0"
			"origin_x" "200"
			"origin_y" "0"
			"origin_z" "-60"
			"frame_origin_x"	"0"
			"frame_origin_y"	"0"
			"frame_origin_z"	"0"
			"spotlight" "1"
		
			"modelname"		""
			
			"animation"
			{
				"name"		"PRIMARY"
				"activity"	"ACT_MP_STAND_PRIMARY"
				"default"	"1"
			}
			"animation"
			{
				"name"		"SECONDARY"
				"activity"	"ACT_MP_STAND_SECONDARY"
			}
			"animation"
			{
				"name"		"MELEE"
				"activity"	"ACT_MP_STAND_MELEE"
			}
			"animation"
			{
				"name"		"BUILDING"
				"activity"	"ACT_MP_STAND_BUILDING"
			}
			"animation"
			{
				"name"		"PDA"
				"activity"	"ACT_MP_STAND_PDA"
			}
			"animation"
			{
				"name"		"ITEM1"
				"activity"	"ACT_MP_STAND_ITEM1"
			}						
			"animation"
			{
				"name"		"ITEM2"
				"activity"	"ACT_MP_STAND_ITEM2"
			}									
			"animation"
			{
				"name"		"MELEE_ALLCLASS"
				"activity"	"ACT_MP_STAND_MELEE_ALLCLASS"
			}
			"animation"
			{
				"name"		"PRIMARY2"
				"activity"	"ACT_MP_STAND_PRIMARY"
			}
			"animation"
			{
				"name"		"SECONDARY2"
				"activity"	"ACT_MP_STAND_SECONDARY2"
			}
		}

		"customclassdata"
		{
			"undefined"
			{
			}
			"Scout"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Sniper"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Soldier"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Demoman"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Medic"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Heavy"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Pyro"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Spy"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
			"Engineer"
			{
				"fov"			"20"
				"angles_x"		"0"
				"angles_y"		"-150"
				"angles_z"		"0"
				"origin_x"		"250"
				"origin_y"		"0"
				"origin_z"		"-49"
			}
		}
	}
}
